function Hd = 60hzfilter
%60HZFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the DSP System Toolbox 8.3.
%
% Generated on: 08-Nov-2013 17:06:52
%

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fnotch = 60;   % Notch Frequency
BW     = 0.1;  % Bandwidth
Apass  = 1;    % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
